ashu/urls.py
from django.contrib import admin
from django.urls import path, include


admin.site.site_header = "Arpit Ice Cream Admin"
admin.site.site_title = "Arpit Ice Cream Admin Portal"
admin.site.index_title = "Welcome to Arpit Ice Creams"



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path("", views.index, name='home'),
    path("contact", views.contact, name='contact'),
    path("about", views.about, name='about'),
    path("register", views.register, name='register'),
    path("login", views.loginUser, name='login'),
    path("logout", views.logoutUser, name='logout'),
]

blog/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Page(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)

class Contact(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=12)
    adr = models.CharField(max_length=200, default='Ratanpur')
    desc = models.TextField()
    # date = models.DateField(default=datetime.today())

    def __str__(self):
        return self.name

blog/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Permission
from blog.models import Contact
from datetime import datetime

# Create your views here.
def index(request):
    return render(request, 'index.html')

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        adr = request.POST.get('adr')
        desc = request.POST.get('desc')
        contact = Contact(name=name , email=email, phone=phone, desc=desc, adr=adr)
        contact.save()
        messages.success(request, 'Your message has been sent')

    return render(request, 'contact.html')

def about(request):
    return render(request, 'about.html')

# user registration
def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()


    context = {'form':form}
    return render(request, 'register.html', context)
    
# User Authenticate
def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)
        # check if user has entered corPOSTrect credentials

        user = authenticate(username=username, password=password)
        # if user is not None:
        #     login(request, user)
        #     return redirect('/')
        # else:
        #     return render(request, 'login.html')

        if username=='arpit':
            login(request, user)
            return redirect('/')
        else:
            login(request, user)
            return redirect('/contact')
    return render(request, 'login.html')

def logoutUser(request):
    logout(request)
    return redirect('/login')

templates/about.html
{% extends 'base.html' %}

<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
</head>


{% block body %}
welcome {{request.user}}
<body class="h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        
        <main class="px-3">
            <h1>Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit
                the text, and add your own fullscreen background photo to make it your own.</p>
            {% comment %} <p class="lead">
                <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
            </p> {% endcomment %}
        </main>

        {% comment %} <footer class="mt-auto text-white-50">
            <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                    href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
        </footer> {% endcomment %}
    </div>
</body>

</html>

{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- Adding manual css -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/> -->

    <title>{% block title %}{% endblock title %} | SuperMart</title>
</head>

<body>
    <!-- for light mode -->
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <!-- for dark mode -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container-fluid">
            <a class="navbar-brand" href="#">SuperMart</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About Us</a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Service
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/services"></a></li>
                            <li><a class="dropdown-item" href="#">softy</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">family-pack</a></li>
                        </ul>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact Us</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

<!-- message alert -->

{% if messages %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}

    {% block body %} {% endblock body %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock title %}
{% block body %}
Welcome {{request.user}}
<div class="container-fluid px-0">
    <img src="/static/img/tile2.jpg" class="d-block w-100" alt="...">
    <div class="container">
        <div class="carousel-caption d-md-block mb-0 pb-0" style="top:75px;">
            <h1 class="text-center">Contact Us</h1>
            <form method="post" action="/contact" class="flex">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your Name">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your Email"
                        aria-describedby="emailHelp">
                    {% comment %} <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div> {% endcomment %}
                </div>
                <div class="mb-3">
                    <label for="Phone" class="form-label">Phone Number</label>
                    <input type="Phone" class="form-control" id="Phone" name="phone"
                        placeholder="Enter your Mobile Number">
                </div>
                {% comment %} address {% endcomment %}
                <div class="mb-3">
                    <label for="adr" class="form-label">Address</label>
                    <input type="text" class="form-control" id="adr" name="adr" placeholder="Enter your Address">
                </div>
                {% comment %} address {% endcomment %}
                <div class="mb-3">
                    <label for="desc" class="form-label">Tell me about what you want to contact me for ...</label>
                    {% comment %} <input type="password" class="form-control" id="exampleInputPassword1"> {% endcomment%}
                    <textarea class="form-control" id="desc" rows="3" name="desc"></textarea>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                {% if perms.blog.view_contact %}
                <input type="button" value="view">
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% comment %} {% extends 'base.html' %}

{% block title %}home{% endblock title %}

{% block body %} {% endcomment %}
{% comment %} Header Slide {% endcomment %}
{% comment %} Welcome {{request.user}}
This is index

<a href="logout">Logout</a>

{% endblock body %}  {% endcomment %}


{% comment %} {% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <title>Home</title>
</head>
<body>
    {% block body %} 
    
    
    {% endblock body %}
</body>
</html> {% endcomment %}



{% block title %}Home{% endblock title %}

{% block body %}
{% comment %} Header Slide {% endcomment %}
Welcome {{request.user}}
<div class="container-fluid px-0">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
            <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                {% comment %} Using the API {% endcomment %}
                {% comment %} <img src="https://source.unsplash.com/1600x600/?icecream" class="d-block w-100" alt="...">
                {% endcomment %}

                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h5>welcome to the best Ice Cream of Kanpur</h5>
                    <p>I know you eat icecreams but I know you have not eaten my icecream so please eat my icecreams</p>
                </div> {% endcomment %}
            </div>
            <div class="carousel-item">
                <img src="/static/img/2.jpeg" class="d-block w-100" alt="...">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h5>We serve love with our Ice Creams</h5>
                    <p>Arpit's World Famous Best Ice Creams.</p>
                </div> {% endcomment %}
            </div>
            <div class="carousel-item">
                <img src="/static/img/3.jpeg" class="d-block w-100" alt="...">
                {% comment %} <div class="carousel-caption d-none d-md-block">
                    <h5>Inaugarated by Narendra Modi</h5>
                    <p>This Ice Cream shop was inaugragted by Honorable Prime Minister Narendra Modi.</p>
                </div> {% endcomment %}
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </a>
    </div>

</div>

{% comment %} content {% endcomment %}
<div class="container my-3">
    <h1 class="my-4 text-center">Select from our range of ice creams</h1>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">

                <img src="/static/img/p1.jpeg" class="d-block w-100" alt="...">

                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card shadow-sm">

                <img src="/static/img/p2.jpeg" class="d-block w-100" alt="...">

                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card shadow-sm">

                <img src="/static/img/p3.jpeg" class="d-block w-100" alt="...">

                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card shadow-sm">

                <img src="/static/img/p4.jpeg" class="d-block w-100" alt="...">

                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card shadow-sm">

                <img src="/static/img/p5.jpeg" class="d-block w-100" alt="...">

                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card shadow-sm">
                <img src="/static/img/p6.jpeg" class="d-block w-100" alt="...">
                <div class="card-body">
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<button type="button"><a href="logout">Logout</a></button>

{% endblock body %}

templates/login.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Welcome to tech world</title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }


        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
</head>

<body class="text-center">

    <main class="form-signin">
        <form method="post" action="/login">
            {% csrf_token %}
            <!-- <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            <label for="inputEmail" class="visually-hidden">Username</label><br>
            <input type="text" id="inputEmail" name="username" class="form-control" placeholder="username" required
                autofocus><br>
            <label for="inputPassword" class="visually-hidden">Password</label>
            <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password"
                required>
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button><br><br>
            <button class="w-100 btn btn-lg btn-primary" type="button">
                <a href="/register">Signup</a>
            </button>
            <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
        </form>
    </main>


</body>

</html>

templates/register.html
Register


<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" name="Create User">
</form>